title: "Towards Better Disentanglement in Non-Autoregressive Zero-Shot Expressive Voice Conversion"
description: |
          Seymanur Akti, Tuan-Nam Nguyen, Alexander Waibel
          Interactive Systems Lab, Karlsruhe Institute of Technology, Germany
theme: jekyll-theme-cayman

sass:
  sass_dir: assets/style/
